name: Hexo

on:
  push:
    branches: [ backend ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Hexo

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          ref: backend

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Hexo Action
        uses: sma11black/hexo-action@v1.0.4
        with:
          deploy_key: ${{ secrets.HEXO }}
